name: Weather Tracker Automation

on:
  schedule:
    - cron: "0 6 * * *" # Runs every day at 6 AM UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¥ Checkout code
        uses: actions/checkout@v3

      - name: ðŸ Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: ðŸ“¦ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread oauth2client gspread-formatting requests

      - name: ðŸ” Write credentials.json from GitHub Secret
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json

      - name: ðŸš€ Run your weather script
        run: python weather_tracker.py

      - name: ðŸ“¤ Upload the weather log (optional)
        uses: actions/upload-artifact@v3
        with:
          name: weather-log
          path: weather_log.txt
