name: Weather Tracker Update

on:
  schedule:
    - cron: '0 0 * * *'  # This runs the workflow daily at midnight UTC.
  workflow_dispatch:  # This allows you to trigger the workflow manually.

jobs:
  update_weather:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run weather script
      run: |
        python weather2.py  # Make sure this file exists in the repo.
